#!/bin/bash

./p4500 -f /course/cs4500f13/Assignments/A4/x1.wav -f /course/cs4500f13/Assignments/A4/x5.wav
./p4500 -f /course/cs4500f13/Assignments/A4/x1.wav -f /course/cs4500f13/Assignments/A4/x8.wav
./p4500 -f /course/cs4500f13/Assignments/A4/x3.wav -f /course/cs4500f13/Assignments/A4/x12.wav
./p4500 -f /course/cs4500f13/Assignments/A4/wayfaring.wav -f /course/cs4500f13/Assignments/A4/x10.wav
./p4500 -f /course/cs4500f13/Assignments/A4/x11.wav -f /course/cs4500f13/Assignments/A4/x12.wav
./p4500 -f /course/cs4500f13/Assignments/A4/hewlett.wav -f /course/cs4500f13/Assignments/A4/x1.wav
./p4500 -f /course/cs4500f13/Assignments/A4/x1.wav -f /course/cs4500f13/Assignments/A4/x9.wav
./p4500 -f /course/cs4500f13/Assignments/A4/x5.wav -f /course/cs4500f13/Assignments/A4/x8.wav
./p4500 -f /course/cs4500f13/Assignments/A4/x6.wav -f /course/cs4500f13/Assignments/A4/x11.wav
